### ISSUE TITLE
Camera Upload broken images

### ISSUE THREAD

**Issue by lukas2511** [haiwen/seafile-iOS#40] opened 2014-12-18 21:42 UTC
Hey,

I am using the Camera Upload feature on my iPhone (~ 700 pictures) and i noticed that sometimes that last taken picture does not get uploaded to my seafile instance correctly.

The client sometimes states that it successfully uploaded the image, but reports its size as 0 byte, which is exactly what i receive on my computers after Sync, an empty file.
I can't even manually reupload it, that always results in the same corrupted file. Not sure if this is an iOS bug or a SeaFile-iOS bug, but since I can handle the same images in BitTorrent Sync and other apps without problems I kinda guess it's a SeaFile-iOS bug.

After restarting the app I am able to manually upload the image to a different location, but it remains broken in Camera Uploads.

**Comment by poetwang** [comment] 2015-01-07 15:35
I can't reproduce the problem. Did it occurs all the time or occasionally？

**Comment by lukas2511** [comment] 2015-01-07 18:40
It occured a few times. Especially problematic was the initial upload of my camera roll (~700 pictures), that hang a few times and didn't upload a couple of pictures, but it also occured on smaller numbers of pictures, and on the smaller numbers it was always the latest picture in the camera roll that was broken.

The bug is so bad that I now again prefer emailing pictures just because I know that it'll work.

I have to admit that I didn't try reinstalling the app or anything, maybe that would fix it, but even than, this shouldn't have happened anyway.

**Comment by githubtobi** [comment] 2015-01-09 21:17
Same issue here while uploading files from iOS locally to the seafile server via a fast WiFi connection. Only with multiple uploade (>2), a single file works.

**Comment by poetwang** [comment] 2015-01-10 05:16
It is a bug, will be fixed soon.

**Comment by poetwang** [comment] 2015-01-20 11:04
fixed in 1.9.3

**Closed by poetwang** 2015-01-20 11:04 UTC
