### ISSUE TITLE
iOS 11: Enable Seafile as FileProvider

### ISSUE THREAD

**Issue by eHanseJoerg** [haiwen/seafile-iOS#166] opened 2017-07-06 09:15 UTC
For iOS 11, Apple has (for the first time!) announced that it is going to have a new "Files" app that lets users place their files centrally and open the same file with different apps, without needing to go via the "share" menu. File Sync Apps like Dropbox, Box, OneDrive will be supported from the get-go.

I think it would be great if the Seafile iOS app can serve as a FileProvider; see here: [developer.apple.com/documentation/fileprovider](https://developer.apple.com/documentation/fileprovider) for details. Maybe you can investigate this option for iOS 11.

![ipadpro-ios11-files-100725384-large](https://user-images.githubusercontent.com/19169901/27904240-517838f8-623c-11e7-9704-e4f81ad27c9c.jpg)

**Comment by poetwang** [comment] 2017-07-09 02:46
Seafile already supported FileProvider

**Comment by onekreg** [comment] 2017-09-18 14:55
I think there need to be made some changes to support the new iOS 11 experience. They changes the api for iOS 11 a lot.

**Comment by onekreg** [comment] 2017-09-18 14:55
I think there need to be made some changes to support the new iOS 11 experience. They changes the api for iOS 11 a lot.

**Comment by denisnone** [comment] 2017-09-25 16:11
Please reopen this issue. 
As FileProvider has changed in iOS 11. 
https://developer.apple.com/documentation/fileprovider/nsfileproviderextension

This is a great session on WWDC 17 explaining NSFileProvider enhancements:
https://developer.apple.com/videos/play/wwdc2017/243/

**Comment by dakira** [comment] 2017-11-22 14:16
@poetwang Support for this would allow other iOS apps to use Seafile to sync their data. This would be really great!

**Comment by poetwang** [comment] 2017-12-10 19:05
fixed in 2.7.0

**Closed by poetwang** 2017-12-10 19:05 UTC

**Comment by eHanseJoerg** [comment] 2017-12-10 21:52
Cinformed, works now with normal folders. Does not work for me with encrypted folders. Is this a bug or simply not possible?

**Comment by poetwang** [comment] 2017-12-11 07:30
Now seafile does not support authentication in Files.app, if touchId is enabled, the account will not appear in Files.app, and if the library password is required, library will not appear. You can enabled local decryption in Seafile app and get into the encrypted library to let seafile remember the password, then you can access the encrypted library in Files.app

**Comment by mburgholte** [comment] 2017-12-12 10:58
I've a problem with synchronisation between Seafile and the files.app. Once I opened a file (for example in pwsafe 2) I can see inside the files.app my folder and file from Seafile. The app pwsafe is not able to open the file cause it is not accessible. After that inside the files.app my filesize is 0 with the date 01.01.70. Inside the Seafile app everything is fine. If I use another device and change my existing file to force a new sync of this file, nothing happes in my files app. So is this a bug?? Thanks.

**Comment by clarity99** [comment] 2019-03-30 20:44
This does not work as of now. I get Authenthication required, you need to authenthicate in seafile app. 
Authenthicating there does nothing for the Files app. Turning off touchid for seafile also has no effect.

**Comment by denisnone** [comment] 2019-03-31 11:00
Yes, I can confirm. Something was broken I suppose. And as I remember this is for long time.  Maybe some APIs should be updated for iOS 12?

**Comment by dakira** [comment] 2019-03-31 20:29
I cannot confirm @clarity99. This works perfectly for me. Last tested right now with iOS 12.1.4, Seafile 2.8.6 and PDF Viewer Pro.

You need to enable Seafile as a FileProvider in the Files app, though.

**Comment by dakira** [comment] 2019-03-31 20:34
Here's a screenshot of the files app.
![IMG_8395](https://user-images.githubusercontent.com/576555/55294673-22fbae80-5405-11e9-993f-620679e1183a.PNG)

**Comment by denisnone** [comment] 2019-04-01 13:49
OK, now I figured out.
This feature does not work if the Touch ID authentication is enabled. 
But to make it work you need not only disable TouchID in Seafile, but also reboot the iPhone.

**Comment by clarity99** [comment] 2019-04-01 14:14
@dakira I'm on ios 12.2 - file provider was enabled, otherwise I wouldn't see SeaFile in locations, after which I got the error. 
Anyways, I figured out the same as @denisnone  - after disabling touchid AND rebooting, it works. Just disabling touchid wasn't enough.
I've reenabled touchid in seafile and it still works, but I haven't rebooted yet.

**Comment by dakira** [comment] 2019-04-01 14:53
@denisnone @clarity99 nice. Great find! Can you report this as a new issue?

**Comment by denisnone** [comment] 2019-04-01 16:12
@dakira 
I'm not quite sure that this is the bug of Seafile. It may be it's iOS 12's bug (or intended behavior), that queries all FileProviders once after boot. Or after app install.
